### ISSUE TITLE
pre-alpha version

### ISSUE THREAD

**Issue by bluee** [sergun/Hangfire.Mongo#2]
Thanks for writing a MongoDB plug-in for Hangfire!

You write it's a pre-alpha, but could you elaborate if it is tested to work, if you plan to work more on it?

**Comment by sergun** [comment]
@bluee I'm using it for personal blog and didn't noticed anything wrong yet. But there was not any serious testing, that is why it's in alpha mode. I would prefer to wait a bit and make it release a bit later once folks try it out.
